### ISSUE TITLE
setup.py test deprecation

### ISSUE THREAD

**Issue by Dawnflash** [cvut/naucse.python.cz#15]
https://github.com/pypa/setuptools/issues/1684
https://pypi.org/project/pytest-runner/

Len upozorňujem, že od 2019 sa odhlasovalo zastaranie setup.py test a prechádza sa na oddelenie testovacích štruktúr od setup.py.

**Comment by hroncok** [comment]
Při přesunu této issue se ztratil můj komentář. Na příští běh `setup.py test` zrušíme.
